### PR TITLE
Prevent auto post when created in draft state

### LINKED ISSUE #301: Automatic posts in detailed aid package post in two different orders
- [ ] Automatic posts in detailed aid package post happens 1) when the package is in draft mode AND 2) when the package becomes published, AND 3) medicines are in two different orders in both automatic posts. 

To reproduce: 
1. Create aid package in draft state - see auto post (the order of medicines in the automatic post is incorrect)
2. Move the aid package status to "published" by checking the box in aid package details page (the order of the medicines in the automatic post is correct) 

Screen Shot 2022-07-29 at 11 45 25
Screen Shot 2022-07-29 at 11 45 57

### PR DESCRIPTION
**Pull request by manuranga**
Fixes #301

### CODE REVIEW

File: admin-portal/src/pages/aidPackage/aidPackage.tsx [hunk 1]
```diff
@@ -100,7 +100,9 @@ export default function CreateAidPackage() {
            */
           aidPackages[packageKey].isPublished = true;
           setAidPackages({ ...aidPackages });
-          AidPackageService.commentPublishedAidPackage(data);
+          if (data.status !== "Draft") {
```
Comment (jayasanka-sack) [inline admin-portal/src/pages/aidPackage/aidPackage.tsx:103]: Let's use the enum.
```suggestion
          if (data.status !== AidPackage.Status.Draft) {
```

**Review by jayasanka-sack — APPROVED** [review]
Thanks @manuranga !
