### PR TITLE
Fix order completion confirmation warning

### LINKED ISSUE #307: Aid package shows $0 pledged, but has moved to the Goal Reached section.
- [ ] Aid package shows $0 pledged, but has moved to the Goal Reached section. 
Screen Shot 2022-07-29 at 17 25 59

Screen Shot 2022-07-29 at 17 25 45

### PR DESCRIPTION
**Pull request by dinuka-rp**
## Purpose
The purpose of this PR is to fix #307

## Goal
Display the confirmation only when changing to a completion state from draft or Published.

### CODE REVIEW

File: admin-portal/src/pages/packageDetails/packageDetails.tsx [hunk 1]
```diff
@@ -92,6 +92,19 @@ export default function PackageDetails() {
       `Are you sure you want to change the status to ${statusToBeChanged}?`
     );
     if (confirmed) {
+      if (
+        aidPackageStatus &&
+        (statusToLevel[aidPackageStatus] === 1 ||
+          statusToLevel[aidPackageStatus] === 2) &&
```
Comment (jayasanka-sack) [inline admin-portal/src/pages/packageDetails/packageDetails.tsx:98]: Use the enum,

aidPackageStatus == AidPackage.Status.Draft || ...

Comment (jayasanka-sack) [reply admin-portal/src/pages/packageDetails/packageDetails.tsx:98]: Suggestion:
Keep an array of completed statuses (or incomplete statuses).
```js
const completedStatuses = [AidPackage.Status.Delivered, ....];
```


then we could check, 
```js
!completedStatuses.includes(aidPackageStatus) && completedStatuses.includes(statusToBeChanged)

```

So that we don't need to mess with numbers when adding a new status.

**Review by jayasanka-sack — CHANGES_REQUESTED** [review]
Thanks for the PR @dinuka-rp !

I added a suggestion

File: admin-portal/src/pages/packageDetails/packageDetails.tsx (hunk 1 above)
Comment (dinuka-rp) [reply admin-portal/src/pages/packageDetails/packageDetails.tsx]: Made the change, as requested in the new commit

**Review by jayasanka-sack — APPROVED** [review]
Thanks @dinuka-rp !
