### PR TITLE
Fix the footer links to scroll to top

### LINKED ISSUE #397: Footer links should scroll to the top
If a user clicks on the footer links .. please take them to the top. e.g. click on about us, take the user to the top of the about us page.

### PR DESCRIPTION
**Pull request by gajindubandara**
## Purpose

The purpose of this PR is to fix #397

## Goals
Fix the footer links to scroll to the page top

## Approach
Fixed the links to scroll to top

### CODE REVIEW

File: donor-portal/src/pages/about-us/index.tsx [hunk 1]
```diff
@@ -10,6 +10,7 @@ import wso2logo from "./images/wso2.png";
 import "./styles.css";
 
 export default function AboutUs() {
+  window.scrollTo({ top: 0, left: 0, behavior: "smooth" });
```
Comment (jayasanka-sack) [inline donor-portal/src/pages/about-us/index.tsx:13]: This will call this function on each re-render. 

A proper fix would be something like this:
https://stackoverflow.com/questions/36904185/react-router-scroll-to-top-on-every-transition

**Review by jayasanka-sack — CHANGES_REQUESTED** [review]
Thanks for the PR @gajindubandara ! Check comments

File: donor-portal/src/pages/about-us/index.tsx (hunk 1 above)
Comment (jayasanka-sack) [reply donor-portal/src/pages/about-us/index.tsx:13]: You can try something like this:

Add the following hook to the app.tsx file. So that it will scroll to the top on every path change. 

const { pathname } = useLocation();

  useEffect(() => {
    window.scrollTo(0, 0);
  }, [pathname]);

**Review by dinuka-rp — APPROVED** [review]
LGTM! Works as expected. Thanks for the PR @gajindubandara !

**Comment by dinuka-rp** [comment]
@jayasanka-sack I don't seem to be able to merge this since u've requested for changes and review

**Review by jayasanka-sack — APPROVED** [review]
Thanks @gajindubandara !
